services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: streaming_api
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - srs

  postgres:
    image: postgres:16-alpine
    container_name: streaming_postgres
    environment:
      POSTGRES_DB: streaming
      POSTGRES_USER: streaming
      POSTGRES_PASSWORD: streaming
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: streaming_redis
    ports:
      - "6379:6379"

  srs:
    image: ossrs/srs:5
    container_name: streaming_srs
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8081:8080"
    command: ["./objs/srs", "-c", "conf/docker.conf"]

  cdn:
    image: nginx:1.27-alpine
    container_name: streaming_cdn
    depends_on:
      - srs
    ports:
      - "8088:8088"
    volumes:
      - ./deployments/nginx/cdn.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
