FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/transcode ./cmd/transcode

FROM alpine:3.22

RUN apk add --no-cache ffmpeg

WORKDIR /app
COPY --from=builder /bin/transcode /usr/local/bin/transcode

CMD ["transcode"]
